"""General Augment Python SDK public import path.

The hand-written :class:`GeneralAugmentClient` is the public facade: it keeps its own
hardened httpx transport (retries with Retry-After, auto-idempotency on create_response,
SSE streaming, dual auth) and dict-based payloads for backwards compatibility. The
typed request/response models in :mod:`genaug.types` are generated by Fern from the
curated public OpenAPI subset and re-exported as the drift-checked typed contract.
"""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from genaug import types
from genaug.agent import AgentClient
from genaug.client import (
    UNSET,
    GeneralAugmentAPIError,
    GeneralAugmentClient,
    response_output_text,
    response_structured_output,
)

try:
    # Single source of truth: the installed distribution version (pyproject.toml).
    __version__ = _pkg_version("general-augment-sdk")
except PackageNotFoundError:  # pragma: no cover - editable/source checkout fallback
    __version__ = "0.0.0+local"

__all__ = [
    "UNSET",
    "AgentClient",
    "GeneralAugmentAPIError",
    "GeneralAugmentClient",
    "__version__",
    "response_output_text",
    "response_structured_output",
    "types",
]
