"""Typed request/response models for the General Augment public API.

These pydantic models are GENERATED by Fern from the curated public OpenAPI subset
(see ``fern/curate_public_overlay.py`` in the monorepo) and re-exported here as the
drift-checked typed contract for the SDK's public surface. The hand-written
:class:`genaug.GeneralAugmentClient` keeps its own hardened httpx transport and uses
dict-based payloads/returns for backwards compatibility; import these models when you
want static typing or validation of the request/response shapes.

The underlying ``genaug._generated`` package is regenerated from the spec and MUST NOT
be hand-edited. Only the curated public operations' models are generated, so nothing
internal (billing, coding runs, browser runs, scheduled jobs, eval, etc.) is exposed.
"""

from __future__ import annotations

from genaug._generated.types import (
    AgentConfigUploadRequest,
    AgentTestRequest,
    AgentTestResponse,
    IdentityResolutionResponse,
    IntegrationPromptResponse,
    LinkChallengeResponse,
    LinkUserRequest,
    MemoryDeleteResponse,
    MemoryDeletionReceipt,
    MemoryFactResponse,
    MemoryProfileResponse,
    MemorySearchResponse,
    MemorySourceResponse,
    MemoryStoreResponse,
    OpenApiToolRegistrationRequest,
    OpenApiToolRegistrationResponse,
    ProjectListResponse,
    ProjectResponse,
    ProjectUpdate,
    ProjectUsageResponse,
    ResponsesResponse,
    ResponsesUsage,
    ResponsesUsageDetails,
    UnlinkResponse,
)

__all__ = [
    "AgentConfigUploadRequest",
    "AgentTestRequest",
    "AgentTestResponse",
    "IdentityResolutionResponse",
    "IntegrationPromptResponse",
    "LinkChallengeResponse",
    "LinkUserRequest",
    "MemoryDeleteResponse",
    "MemoryDeletionReceipt",
    "MemoryFactResponse",
    "MemoryProfileResponse",
    "MemorySearchResponse",
    "MemorySourceResponse",
    "MemoryStoreResponse",
    "OpenApiToolRegistrationRequest",
    "OpenApiToolRegistrationResponse",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectUpdate",
    "ProjectUsageResponse",
    "ResponsesResponse",
    "ResponsesUsage",
    "ResponsesUsageDetails",
    "UnlinkResponse",
]
