# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.memory_delete_response import MemoryDeleteResponse
from ..types.memory_profile_response import MemoryProfileResponse
from ..types.memory_search_response import MemorySearchResponse
from ..types.memory_store_response import MemoryStoreResponse
from .raw_client import AsyncRawAgentClient, RawAgentClient
from .types.memory_search_request_fact_type import MemorySearchRequestFactType
from .types.memory_store_request_fact_type import MemoryStoreRequestFactType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentClient
        """
        return self._raw_client

    def memory_profile(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryProfileResponse:
        """
        Return one tenant user's stored profile and recent memory facts.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryProfileResponse
            Successful Response

        Examples
        --------
        from general_augment import GeneralAugmentClient

        client = GeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )
        client.agent.memory_profile(
            user_id="user_id",
        )
        """
        _response = self._raw_client.memory_profile(user_id, agent_run_id=agent_run_id, request_options=request_options)
        return _response.data

    def search_memory(
        self,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        fact_type: typing.Optional[MemorySearchRequestFactType] = OMIT,
        include_sensitive: typing.Optional[bool] = OMIT,
        limit: typing.Optional[int] = OMIT,
        min_importance: typing.Optional[float] = OMIT,
        min_similarity: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        source: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemorySearchResponse:
        """
        Semantically search one tenant user's memories.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        created_after : typing.Optional[dt.datetime]

        fact_type : typing.Optional[MemorySearchRequestFactType]

        include_sensitive : typing.Optional[bool]

        limit : typing.Optional[int]

        min_importance : typing.Optional[float]

        min_similarity : typing.Optional[float]

        query : typing.Optional[str]

        source : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemorySearchResponse
            Successful Response

        Examples
        --------
        from general_augment import GeneralAugmentClient

        client = GeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )
        client.agent.search_memory(
            user_id="user_id",
        )
        """
        _response = self._raw_client.search_memory(
            user_id=user_id,
            agent_run_id=agent_run_id,
            collection_key=collection_key,
            created_after=created_after,
            fact_type=fact_type,
            include_sensitive=include_sensitive,
            limit=limit,
            min_importance=min_importance,
            min_similarity=min_similarity,
            query=query,
            source=source,
            request_options=request_options,
        )
        return _response.data

    def store_memory(
        self,
        *,
        fact: str,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        fact_type: typing.Optional[MemoryStoreRequestFactType] = OMIT,
        idempotency_key: typing.Optional[str] = OMIT,
        importance_score: typing.Optional[float] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        source: typing.Optional[str] = OMIT,
        user_profile: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryStoreResponse:
        """
        Store one explicit memory fact for a tenant user.

        Parameters
        ----------
        fact : str

        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        fact_type : typing.Optional[MemoryStoreRequestFactType]

        idempotency_key : typing.Optional[str]

        importance_score : typing.Optional[float]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        source : typing.Optional[str]

        user_profile : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryStoreResponse
            Successful Response

        Examples
        --------
        from general_augment import GeneralAugmentClient

        client = GeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )
        client.agent.store_memory(
            fact="fact",
            user_id="user_id",
        )
        """
        _response = self._raw_client.store_memory(
            fact=fact,
            user_id=user_id,
            agent_run_id=agent_run_id,
            collection_key=collection_key,
            fact_type=fact_type,
            idempotency_key=idempotency_key,
            importance_score=importance_score,
            metadata=metadata,
            source=source,
            user_profile=user_profile,
            request_options=request_options,
        )
        return _response.data

    def purge_user_memory(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryDeleteResponse:
        """
        Delete all memories for one external application user.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryDeleteResponse
            Successful Response

        Examples
        --------
        from general_augment import GeneralAugmentClient

        client = GeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )
        client.agent.purge_user_memory(
            user_id="user_id",
        )
        """
        _response = self._raw_client.purge_user_memory(
            user_id, agent_run_id=agent_run_id, request_options=request_options
        )
        return _response.data

    def delete_memory(
        self,
        memory_id: str,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryDeleteResponse:
        """
        Delete one memory fact for one external application user.

        Parameters
        ----------
        memory_id : str

        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryDeleteResponse
            Successful Response

        Examples
        --------
        from general_augment import GeneralAugmentClient

        client = GeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )
        client.agent.delete_memory(
            memory_id="memory_id",
            user_id="user_id",
        )
        """
        _response = self._raw_client.delete_memory(
            memory_id, user_id=user_id, agent_run_id=agent_run_id, request_options=request_options
        )
        return _response.data


class AsyncAgentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentClient
        """
        return self._raw_client

    async def memory_profile(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryProfileResponse:
        """
        Return one tenant user's stored profile and recent memory facts.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryProfileResponse
            Successful Response

        Examples
        --------
        import asyncio

        from general_augment import AsyncGeneralAugmentClient

        client = AsyncGeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )


        async def main() -> None:
            await client.agent.memory_profile(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.memory_profile(
            user_id, agent_run_id=agent_run_id, request_options=request_options
        )
        return _response.data

    async def search_memory(
        self,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        fact_type: typing.Optional[MemorySearchRequestFactType] = OMIT,
        include_sensitive: typing.Optional[bool] = OMIT,
        limit: typing.Optional[int] = OMIT,
        min_importance: typing.Optional[float] = OMIT,
        min_similarity: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        source: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemorySearchResponse:
        """
        Semantically search one tenant user's memories.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        created_after : typing.Optional[dt.datetime]

        fact_type : typing.Optional[MemorySearchRequestFactType]

        include_sensitive : typing.Optional[bool]

        limit : typing.Optional[int]

        min_importance : typing.Optional[float]

        min_similarity : typing.Optional[float]

        query : typing.Optional[str]

        source : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemorySearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from general_augment import AsyncGeneralAugmentClient

        client = AsyncGeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )


        async def main() -> None:
            await client.agent.search_memory(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_memory(
            user_id=user_id,
            agent_run_id=agent_run_id,
            collection_key=collection_key,
            created_after=created_after,
            fact_type=fact_type,
            include_sensitive=include_sensitive,
            limit=limit,
            min_importance=min_importance,
            min_similarity=min_similarity,
            query=query,
            source=source,
            request_options=request_options,
        )
        return _response.data

    async def store_memory(
        self,
        *,
        fact: str,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        fact_type: typing.Optional[MemoryStoreRequestFactType] = OMIT,
        idempotency_key: typing.Optional[str] = OMIT,
        importance_score: typing.Optional[float] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        source: typing.Optional[str] = OMIT,
        user_profile: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryStoreResponse:
        """
        Store one explicit memory fact for a tenant user.

        Parameters
        ----------
        fact : str

        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        fact_type : typing.Optional[MemoryStoreRequestFactType]

        idempotency_key : typing.Optional[str]

        importance_score : typing.Optional[float]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        source : typing.Optional[str]

        user_profile : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryStoreResponse
            Successful Response

        Examples
        --------
        import asyncio

        from general_augment import AsyncGeneralAugmentClient

        client = AsyncGeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )


        async def main() -> None:
            await client.agent.store_memory(
                fact="fact",
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.store_memory(
            fact=fact,
            user_id=user_id,
            agent_run_id=agent_run_id,
            collection_key=collection_key,
            fact_type=fact_type,
            idempotency_key=idempotency_key,
            importance_score=importance_score,
            metadata=metadata,
            source=source,
            user_profile=user_profile,
            request_options=request_options,
        )
        return _response.data

    async def purge_user_memory(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryDeleteResponse:
        """
        Delete all memories for one external application user.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryDeleteResponse
            Successful Response

        Examples
        --------
        import asyncio

        from general_augment import AsyncGeneralAugmentClient

        client = AsyncGeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )


        async def main() -> None:
            await client.agent.purge_user_memory(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.purge_user_memory(
            user_id, agent_run_id=agent_run_id, request_options=request_options
        )
        return _response.data

    async def delete_memory(
        self,
        memory_id: str,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryDeleteResponse:
        """
        Delete one memory fact for one external application user.

        Parameters
        ----------
        memory_id : str

        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryDeleteResponse
            Successful Response

        Examples
        --------
        import asyncio

        from general_augment import AsyncGeneralAugmentClient

        client = AsyncGeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )


        async def main() -> None:
            await client.agent.delete_memory(
                memory_id="memory_id",
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_memory(
            memory_id, user_id=user_id, agent_run_id=agent_run_id, request_options=request_options
        )
        return _response.data
