# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from ..types.memory_delete_response import MemoryDeleteResponse
from ..types.memory_profile_response import MemoryProfileResponse
from ..types.memory_search_response import MemorySearchResponse
from ..types.memory_store_response import MemoryStoreResponse
from .types.memory_search_request_fact_type import MemorySearchRequestFactType
from .types.memory_store_request_fact_type import MemoryStoreRequestFactType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAgentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def memory_profile(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MemoryProfileResponse]:
        """
        Return one tenant user's stored profile and recent memory facts.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MemoryProfileResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memory/profile/{encode_path_param(user_id)}",
            method="GET",
            params={
                "agent_run_id": agent_run_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryProfileResponse,
                    parse_obj_as(
                        type_=MemoryProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def search_memory(
        self,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        fact_type: typing.Optional[MemorySearchRequestFactType] = OMIT,
        include_sensitive: typing.Optional[bool] = OMIT,
        limit: typing.Optional[int] = OMIT,
        min_importance: typing.Optional[float] = OMIT,
        min_similarity: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        source: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MemorySearchResponse]:
        """
        Semantically search one tenant user's memories.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        created_after : typing.Optional[dt.datetime]

        fact_type : typing.Optional[MemorySearchRequestFactType]

        include_sensitive : typing.Optional[bool]

        limit : typing.Optional[int]

        min_importance : typing.Optional[float]

        min_similarity : typing.Optional[float]

        query : typing.Optional[str]

        source : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MemorySearchResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/agent/memory/search",
            method="POST",
            json={
                "agent_run_id": agent_run_id,
                "collection_key": collection_key,
                "created_after": created_after,
                "fact_type": fact_type,
                "include_sensitive": include_sensitive,
                "limit": limit,
                "min_importance": min_importance,
                "min_similarity": min_similarity,
                "query": query,
                "source": source,
                "user_id": user_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemorySearchResponse,
                    parse_obj_as(
                        type_=MemorySearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def store_memory(
        self,
        *,
        fact: str,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        fact_type: typing.Optional[MemoryStoreRequestFactType] = OMIT,
        idempotency_key: typing.Optional[str] = OMIT,
        importance_score: typing.Optional[float] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        source: typing.Optional[str] = OMIT,
        user_profile: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MemoryStoreResponse]:
        """
        Store one explicit memory fact for a tenant user.

        Parameters
        ----------
        fact : str

        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        fact_type : typing.Optional[MemoryStoreRequestFactType]

        idempotency_key : typing.Optional[str]

        importance_score : typing.Optional[float]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        source : typing.Optional[str]

        user_profile : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MemoryStoreResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/agent/memory/store",
            method="POST",
            json={
                "agent_run_id": agent_run_id,
                "collection_key": collection_key,
                "fact": fact,
                "fact_type": fact_type,
                "idempotency_key": idempotency_key,
                "importance_score": importance_score,
                "metadata": metadata,
                "source": source,
                "user_id": user_id,
                "user_profile": user_profile,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryStoreResponse,
                    parse_obj_as(
                        type_=MemoryStoreResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def purge_user_memory(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MemoryDeleteResponse]:
        """
        Delete all memories for one external application user.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MemoryDeleteResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memory/user/{encode_path_param(user_id)}",
            method="DELETE",
            params={
                "agent_run_id": agent_run_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryDeleteResponse,
                    parse_obj_as(
                        type_=MemoryDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_memory(
        self,
        memory_id: str,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MemoryDeleteResponse]:
        """
        Delete one memory fact for one external application user.

        Parameters
        ----------
        memory_id : str

        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MemoryDeleteResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memory/{encode_path_param(memory_id)}",
            method="DELETE",
            params={
                "user_id": user_id,
                "agent_run_id": agent_run_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryDeleteResponse,
                    parse_obj_as(
                        type_=MemoryDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAgentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def memory_profile(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MemoryProfileResponse]:
        """
        Return one tenant user's stored profile and recent memory facts.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MemoryProfileResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memory/profile/{encode_path_param(user_id)}",
            method="GET",
            params={
                "agent_run_id": agent_run_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryProfileResponse,
                    parse_obj_as(
                        type_=MemoryProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def search_memory(
        self,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        fact_type: typing.Optional[MemorySearchRequestFactType] = OMIT,
        include_sensitive: typing.Optional[bool] = OMIT,
        limit: typing.Optional[int] = OMIT,
        min_importance: typing.Optional[float] = OMIT,
        min_similarity: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        source: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MemorySearchResponse]:
        """
        Semantically search one tenant user's memories.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        created_after : typing.Optional[dt.datetime]

        fact_type : typing.Optional[MemorySearchRequestFactType]

        include_sensitive : typing.Optional[bool]

        limit : typing.Optional[int]

        min_importance : typing.Optional[float]

        min_similarity : typing.Optional[float]

        query : typing.Optional[str]

        source : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MemorySearchResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/agent/memory/search",
            method="POST",
            json={
                "agent_run_id": agent_run_id,
                "collection_key": collection_key,
                "created_after": created_after,
                "fact_type": fact_type,
                "include_sensitive": include_sensitive,
                "limit": limit,
                "min_importance": min_importance,
                "min_similarity": min_similarity,
                "query": query,
                "source": source,
                "user_id": user_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemorySearchResponse,
                    parse_obj_as(
                        type_=MemorySearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def store_memory(
        self,
        *,
        fact: str,
        user_id: str,
        agent_run_id: typing.Optional[str] = OMIT,
        collection_key: typing.Optional[str] = OMIT,
        fact_type: typing.Optional[MemoryStoreRequestFactType] = OMIT,
        idempotency_key: typing.Optional[str] = OMIT,
        importance_score: typing.Optional[float] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        source: typing.Optional[str] = OMIT,
        user_profile: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MemoryStoreResponse]:
        """
        Store one explicit memory fact for a tenant user.

        Parameters
        ----------
        fact : str

        user_id : str

        agent_run_id : typing.Optional[str]

        collection_key : typing.Optional[str]

        fact_type : typing.Optional[MemoryStoreRequestFactType]

        idempotency_key : typing.Optional[str]

        importance_score : typing.Optional[float]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        source : typing.Optional[str]

        user_profile : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MemoryStoreResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/agent/memory/store",
            method="POST",
            json={
                "agent_run_id": agent_run_id,
                "collection_key": collection_key,
                "fact": fact,
                "fact_type": fact_type,
                "idempotency_key": idempotency_key,
                "importance_score": importance_score,
                "metadata": metadata,
                "source": source,
                "user_id": user_id,
                "user_profile": user_profile,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryStoreResponse,
                    parse_obj_as(
                        type_=MemoryStoreResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def purge_user_memory(
        self,
        user_id: str,
        *,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MemoryDeleteResponse]:
        """
        Delete all memories for one external application user.

        Parameters
        ----------
        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MemoryDeleteResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memory/user/{encode_path_param(user_id)}",
            method="DELETE",
            params={
                "agent_run_id": agent_run_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryDeleteResponse,
                    parse_obj_as(
                        type_=MemoryDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_memory(
        self,
        memory_id: str,
        *,
        user_id: str,
        agent_run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MemoryDeleteResponse]:
        """
        Delete one memory fact for one external application user.

        Parameters
        ----------
        memory_id : str

        user_id : str

        agent_run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MemoryDeleteResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memory/{encode_path_param(memory_id)}",
            method="DELETE",
            params={
                "user_id": user_id,
                "agent_run_id": agent_run_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MemoryDeleteResponse,
                    parse_obj_as(
                        type_=MemoryDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
