# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent_config_upload_request import AgentConfigUploadRequest
    from .agent_test_request import AgentTestRequest
    from .agent_test_response import AgentTestResponse
    from .approval_policy_config import ApprovalPolicyConfig
    from .http_validation_error import HttpValidationError
    from .identity_resolution_response import IdentityResolutionResponse
    from .integration_prompt_response import IntegrationPromptResponse
    from .link_challenge_response import LinkChallengeResponse
    from .link_user_request import LinkUserRequest
    from .memory_delete_response import MemoryDeleteResponse
    from .memory_delete_response_status import MemoryDeleteResponseStatus
    from .memory_deletion_receipt import MemoryDeletionReceipt
    from .memory_deletion_receipt_operation import MemoryDeletionReceiptOperation
    from .memory_fact_response import MemoryFactResponse
    from .memory_profile_response import MemoryProfileResponse
    from .memory_search_response import MemorySearchResponse
    from .memory_source_response import MemorySourceResponse
    from .memory_store_response import MemoryStoreResponse
    from .open_api_tool_registration_request import OpenApiToolRegistrationRequest
    from .open_api_tool_registration_response import OpenApiToolRegistrationResponse
    from .project_list_response import ProjectListResponse
    from .project_response import ProjectResponse
    from .project_update import ProjectUpdate
    from .project_usage_response import ProjectUsageResponse
    from .responses_output_usage_details import ResponsesOutputUsageDetails
    from .responses_reasoning import ResponsesReasoning
    from .responses_reasoning_effort import ResponsesReasoningEffort
    from .responses_response import ResponsesResponse
    from .responses_response_object import ResponsesResponseObject
    from .responses_response_status import ResponsesResponseStatus
    from .responses_usage import ResponsesUsage
    from .responses_usage_details import ResponsesUsageDetails
    from .tool_discovery_config import ToolDiscoveryConfig
    from .unlink_response import UnlinkResponse
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
_dynamic_imports: typing.Dict[str, str] = {
    "AgentConfigUploadRequest": ".agent_config_upload_request",
    "AgentTestRequest": ".agent_test_request",
    "AgentTestResponse": ".agent_test_response",
    "ApprovalPolicyConfig": ".approval_policy_config",
    "HttpValidationError": ".http_validation_error",
    "IdentityResolutionResponse": ".identity_resolution_response",
    "IntegrationPromptResponse": ".integration_prompt_response",
    "LinkChallengeResponse": ".link_challenge_response",
    "LinkUserRequest": ".link_user_request",
    "MemoryDeleteResponse": ".memory_delete_response",
    "MemoryDeleteResponseStatus": ".memory_delete_response_status",
    "MemoryDeletionReceipt": ".memory_deletion_receipt",
    "MemoryDeletionReceiptOperation": ".memory_deletion_receipt_operation",
    "MemoryFactResponse": ".memory_fact_response",
    "MemoryProfileResponse": ".memory_profile_response",
    "MemorySearchResponse": ".memory_search_response",
    "MemorySourceResponse": ".memory_source_response",
    "MemoryStoreResponse": ".memory_store_response",
    "OpenApiToolRegistrationRequest": ".open_api_tool_registration_request",
    "OpenApiToolRegistrationResponse": ".open_api_tool_registration_response",
    "ProjectListResponse": ".project_list_response",
    "ProjectResponse": ".project_response",
    "ProjectUpdate": ".project_update",
    "ProjectUsageResponse": ".project_usage_response",
    "ResponsesOutputUsageDetails": ".responses_output_usage_details",
    "ResponsesReasoning": ".responses_reasoning",
    "ResponsesReasoningEffort": ".responses_reasoning_effort",
    "ResponsesResponse": ".responses_response",
    "ResponsesResponseObject": ".responses_response_object",
    "ResponsesResponseStatus": ".responses_response_status",
    "ResponsesUsage": ".responses_usage",
    "ResponsesUsageDetails": ".responses_usage_details",
    "ToolDiscoveryConfig": ".tool_discovery_config",
    "UnlinkResponse": ".unlink_response",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentConfigUploadRequest",
    "AgentTestRequest",
    "AgentTestResponse",
    "ApprovalPolicyConfig",
    "HttpValidationError",
    "IdentityResolutionResponse",
    "IntegrationPromptResponse",
    "LinkChallengeResponse",
    "LinkUserRequest",
    "MemoryDeleteResponse",
    "MemoryDeleteResponseStatus",
    "MemoryDeletionReceipt",
    "MemoryDeletionReceiptOperation",
    "MemoryFactResponse",
    "MemoryProfileResponse",
    "MemorySearchResponse",
    "MemorySourceResponse",
    "MemoryStoreResponse",
    "OpenApiToolRegistrationRequest",
    "OpenApiToolRegistrationResponse",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectUpdate",
    "ProjectUsageResponse",
    "ResponsesOutputUsageDetails",
    "ResponsesReasoning",
    "ResponsesReasoningEffort",
    "ResponsesResponse",
    "ResponsesResponseObject",
    "ResponsesResponseStatus",
    "ResponsesUsage",
    "ResponsesUsageDetails",
    "ToolDiscoveryConfig",
    "UnlinkResponse",
    "ValidationError",
    "ValidationErrorLocItem",
]
