# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentTestResponse(UniversalBaseModel):
    """
    Agent test endpoint response.
    """

    cost_usd: typing.Optional[float] = None
    details: typing.Optional[str] = None
    error: typing.Optional[str] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    model_used: typing.Optional[str] = None
    response: typing.Optional[str] = None
    response_text: typing.Optional[str] = None
    suggestion: typing.Optional[str] = None
    warnings: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
