# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentConfigUploadRequest(UniversalBaseModel):
    """
    Payload for importing a `genaug-agent.yaml` document.
    """

    skills: typing.Optional[typing.List[str]] = None
    soul_content: typing.Optional[str] = None
    yaml_content: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
