# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IdentityResolutionResponse(UniversalBaseModel):
    """
    Resolved external app identity response.
    """

    linked_at: typing.Optional[dt.datetime] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    phone_e164: str
    project_id: str
    provider_name: str
    provider_user_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
