# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LinkChallengeResponse(UniversalBaseModel):
    """
    Challenge response returned after a link is initiated.
    """

    debug_verification_code: typing.Optional[str] = None
    id: str
    magic_link: typing.Optional[str] = None
    phone_e164: str
    provider_name: str
    provider_user_id: str
    verification_expires_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
