# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_fact_response import MemoryFactResponse


class MemoryProfileResponse(UniversalBaseModel):
    """
    Persisted memory profile for one tenant user.
    """

    general_augment_user_id: str
    profile: typing.Dict[str, typing.Any]
    recent_facts: typing.List[MemoryFactResponse]
    total_facts: int
    user_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
