# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_deletion_receipt_operation import MemoryDeletionReceiptOperation


class MemoryDeletionReceipt(UniversalBaseModel):
    """
    Receipt returned after a tenant-facing memory delete request commits.
    """

    deleted_count: int
    issued_at: dt.datetime
    operation: MemoryDeletionReceiptOperation
    receipt_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
