# This file was auto-generated by Fern from our API Definition.

import typing

MemoryDeletionReceiptOperation = typing.Union[
    typing.Literal["memory_delete", "memory_purge", "memory_suppress"], typing.Any
]
