# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_source_response import MemorySourceResponse


class MemoryStoreResponse(UniversalBaseModel):
    """
    Response returned after storing a memory fact.
    """

    collection_key: typing.Optional[str] = None
    content: str
    general_augment_user_id: str
    memory_id: str
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    source: typing.Optional[str] = None
    source_info: typing.Optional[MemorySourceResponse] = None
    status: typing.Optional[str] = None
    user_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
