# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_fact_response import MemoryFactResponse


class MemorySearchResponse(UniversalBaseModel):
    """
    Semantic memory search response.
    """

    facts: typing.List[MemoryFactResponse]
    general_augment_user_id: str
    user_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
