# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MemoryFactResponse(UniversalBaseModel):
    """
    Serialized memory fact returned by the tenant-facing API.
    """

    collection_key: typing.Optional[str] = None
    consolidation_group_id: typing.Optional[str] = None
    content: str
    contradicts_memory_id: typing.Optional[str] = None
    created_at: dt.datetime
    expires_at: typing.Optional[dt.datetime] = None
    fact_type: str
    id: str
    importance_score: float
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    parent_memory_id: typing.Optional[str] = None
    provenance: typing.Optional[typing.Dict[str, typing.Any]] = None
    similarity: typing.Optional[float] = None
    source: typing.Optional[str] = None
    status: typing.Optional[str] = None
    supersedes_memory_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
