# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MemorySourceResponse(UniversalBaseModel):
    """
    Project-scoped memory source registry evidence.
    """

    fact_count: int
    id: str
    last_seen_at: typing.Optional[dt.datetime] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    source_key: str
    source_type: str
    status: str
    trust_level: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
