# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_delete_response_status import MemoryDeleteResponseStatus
from .memory_deletion_receipt import MemoryDeletionReceipt


class MemoryDeleteResponse(UniversalBaseModel):
    """
    Response returned after deleting selected memory facts.
    """

    deleted_count: int
    deleted_ids: typing.Optional[typing.List[str]] = None
    general_augment_user_id: str
    memory_id: typing.Optional[str] = None
    receipt: MemoryDeletionReceipt
    status: MemoryDeleteResponseStatus
    user_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
