# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OpenApiToolRegistrationRequest(UniversalBaseModel):
    """
    Payload for generating project tools from an OpenAPI specification.
    """

    auto_deploy: typing.Optional[bool] = None
    exclude_paths: typing.Optional[typing.List[str]] = None
    include_paths: typing.Optional[typing.List[str]] = None
    name_prefix: typing.Optional[str] = None
    spec_url: str
    target_count: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
