# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OpenApiToolRegistrationResponse(UniversalBaseModel):
    """
    Curated generated tool registration response.
    """

    api_title: str
    auto_deployed: bool
    curated_count: int
    enabled_tool_ids: typing.List[str]
    endpoint_count: int
    generated_count: int
    mcp_server: typing.Dict[str, typing.Any]
    tools: typing.List[typing.Dict[str, typing.Any]]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
