# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tool_discovery_config import ToolDiscoveryConfig


class ProjectUpdate(UniversalBaseModel):
    """
    Payload for updating a project tenant.
    """

    approval_webhook_url: typing.Optional[str] = None
    billing_webhook_url: typing.Optional[str] = None
    branding: typing.Optional[typing.Dict[str, typing.Any]] = None
    enabled_tool_ids: typing.Optional[typing.List[str]] = None
    local_connectors: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    mcp_servers: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    model_preferences: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    name: typing.Optional[str] = None
    plan: typing.Optional[str] = None
    platform_webhook_url: typing.Optional[str] = None
    pricing_tier: typing.Optional[str] = None
    rate_limits: typing.Optional[typing.Dict[str, typing.Any]] = None
    security_flags: typing.Optional[typing.Dict[str, typing.Any]] = None
    slug: typing.Optional[str] = None
    status: typing.Optional[str] = None
    system_prompt: typing.Optional[str] = None
    telegram_bot_token: typing.Optional[str] = None
    tool_discovery: typing.Optional[ToolDiscoveryConfig] = None
    twilio_phone_number: typing.Optional[str] = None
    webhook_secret: typing.Optional[str] = None
    whatsapp_phone_number_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
