# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProjectUsageResponse(UniversalBaseModel):
    """
    Detailed usage and cost aggregates for one project.
    """

    days: typing.List[typing.Dict[str, typing.Any]]
    end_date: str
    limits: typing.Optional[typing.Dict[str, typing.Any]] = None
    project_id: str
    start_date: str
    totals: typing.Dict[str, typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
