# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tool_discovery_config import ToolDiscoveryConfig


class ProjectResponse(UniversalBaseModel):
    """
    Serialized project tenant.
    """

    approval_webhook_url: typing.Optional[str] = None
    billing_webhook_url: typing.Optional[str] = None
    branding: typing.Dict[str, typing.Any]
    created_at: dt.datetime
    enabled_tool_ids: typing.List[str]
    id: str
    langfuse_project_id: typing.Optional[str] = None
    langfuse_public_key: typing.Optional[str] = None
    launch_approval_policy: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-owned launch authorization policy. Manifests and installer credentials cannot change this value.
    """

    local_connectors: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    mcp_servers: typing.List[typing.Dict[str, typing.Any]]
    model_preferences: typing.Dict[str, str]
    name: str
    plan: typing.Optional[str] = None
    platform_webhook_url: typing.Optional[str] = None
    pricing_tier: typing.Optional[str] = None
    rate_limits: typing.Dict[str, typing.Any]
    security_flags: typing.Dict[str, typing.Any]
    slug: str
    status: str
    stripe_customer_id: typing.Optional[str] = None
    system_prompt: str
    telegram_bot_configured: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether Telegram credentials are configured without exposing token material.
    """

    telegram_bot_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Always redacted to null in project responses; use telegram_bot_configured for status.
    """

    tool_discovery: typing.Optional[ToolDiscoveryConfig] = None
    twilio_phone_number: typing.Optional[str] = None
    updated_at: dt.datetime
    webhook_secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    Always redacted to null in project responses; send webhook_secret only when rotating the value.
    """

    webhook_secret_configured: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether a project webhook secret exists without exposing secret material.
    """

    webhook_secret_preview: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display-only project webhook secret preview.
    """

    whatsapp_phone_number_id: typing.Optional[str] = None
    workspace_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
