# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .responses_reasoning import ResponsesReasoning
from .responses_response_object import ResponsesResponseObject
from .responses_response_status import ResponsesResponseStatus
from .responses_usage import ResponsesUsage


class ResponsesResponse(UniversalBaseModel):
    """
    Open Responses-compatible response object.
    """

    created_at: int
    error: typing.Optional[typing.Dict[str, typing.Any]] = None
    id: str
    incomplete_details: typing.Optional[typing.Dict[str, typing.Any]] = None
    instructions: typing.Optional[str] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    model: str
    object: typing.Optional[ResponsesResponseObject] = None
    output: typing.List[typing.Dict[str, typing.Any]]
    previous_response_id: typing.Optional[str] = None
    reasoning: typing.Optional[ResponsesReasoning] = None
    status: ResponsesResponseStatus
    temperature: typing.Optional[float] = None
    tools: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    top_p: typing.Optional[float] = None
    usage: ResponsesUsage

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
