# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .responses_output_usage_details import ResponsesOutputUsageDetails
from .responses_usage_details import ResponsesUsageDetails


class ResponsesUsage(UniversalBaseModel):
    """
    Responses-compatible usage payload.
    """

    input_tokens: typing.Optional[int] = None
    input_tokens_details: typing.Optional[ResponsesUsageDetails] = None
    output_tokens: typing.Optional[int] = None
    output_tokens_details: typing.Optional[ResponsesOutputUsageDetails] = None
    total_tokens: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
