# This file was auto-generated by Fern from our API Definition.

import typing

ResponsesResponseStatus = typing.Union[
    typing.Literal["queued", "in_progress", "completed", "failed", "incomplete", "cancelled"], typing.Any
]
