# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .approval_policy_config import ApprovalPolicyConfig


class ToolDiscoveryConfig(UniversalBaseModel):
    """
    Tenant controls for how Hermes sees enabled tools.
    """

    allow_runtime_skill_writes: typing.Optional[bool] = None
    approval_policy: typing.Optional[ApprovalPolicyConfig] = None
    direct_schema_tool_limit: typing.Optional[int] = None
    hermes_runtime: typing.Optional[typing.Dict[str, typing.Any]] = None
    max_search_results: typing.Optional[int] = None
    mode: typing.Optional[str] = None
    native_hermes_toolsets: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
