// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         memory_id: "memory_id",
 *         user_id: "user_id"
 *     }
 */
export interface DeleteMemoryApiV1AgentMemoryMemoryIdDeleteRequest {
    memory_id: string;
    user_id: string;
    agent_run_id?: string | null;
}
