// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: "user_id"
 *     }
 */
export interface MemorySearchRequest {
    agent_run_id?: string | null;
    collection_key?: string | null;
    created_after?: string | null;
    fact_type?: MemorySearchRequest.FactType | null;
    include_sensitive?: boolean;
    limit?: number;
    min_importance?: number | null;
    min_similarity?: number;
    query?: string;
    source?: string | null;
    user_id: string;
}

export namespace MemorySearchRequest {
    export const FactType = {
        Preference: "preference",
        Fact: "fact",
        Entity: "entity",
        Summary: "summary",
    } as const;
    export type FactType = (typeof FactType)[keyof typeof FactType];
}
