// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fact: "fact",
 *         user_id: "user_id"
 *     }
 */
export interface MemoryStoreRequest {
    agent_run_id?: string | null;
    collection_key?: string | null;
    fact: string;
    fact_type?: MemoryStoreRequest.FactType;
    idempotency_key?: string | null;
    importance_score?: number;
    metadata?: Record<string, unknown>;
    source?: string | null;
    user_id: string;
    user_profile?: Record<string, unknown>;
}

export namespace MemoryStoreRequest {
    export const FactType = {
        Preference: "preference",
        Fact: "fact",
        Entity: "entity",
        Summary: "summary",
    } as const;
    export type FactType = (typeof FactType)[keyof typeof FactType];
}
