// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: "user_id"
 *     }
 */
export interface PurgeUserMemoryApiV1AgentMemoryUserUserIdDeleteRequest {
    user_id: string;
    agent_run_id?: string | null;
}
