// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "model"
 *     }
 */
export interface ResponsesRequest {
    "X-Agent-ID"?: string | null;
    "X-Deployment-ID"?: string | null;
    agent?: string | null;
    background?: boolean;
    conversation?: string | null;
    include?: string[] | null;
    input?: unknown;
    instructions?: string | null;
    max_output_tokens?: number | null;
    metadata?: Record<string, unknown>;
    model: string;
    parallel_tool_calls?: boolean;
    previous_response_id?: string | null;
    reasoning?: GeneralAugment.ResponsesReasoning | null;
    reasoning_effort?: ResponsesRequest.ReasoningEffort | null;
    service_tier?: string | null;
    store?: boolean;
    stream?: boolean;
    temperature?: number | null;
    text?: Record<string, unknown> | null;
    tool_choice?: unknown | null;
    tools?: Record<string, unknown>[] | null;
    top_p?: number | null;
    truncation?: ResponsesRequest.Truncation | null;
    user?: string | null;
}

export namespace ResponsesRequest {
    export const ReasoningEffort = {
        None: "none",
        Minimal: "minimal",
        Low: "low",
        Medium: "medium",
        High: "high",
        Xhigh: "xhigh",
    } as const;
    export type ReasoningEffort = (typeof ReasoningEffort)[keyof typeof ReasoningEffort];
    export const Truncation = {
        Disabled: "disabled",
        Auto: "auto",
    } as const;
    export type Truncation = (typeof Truncation)[keyof typeof Truncation];
}
