# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AgentConfigUploadRequest,
        AgentTestRequest,
        AgentTestResponse,
        ApprovalPolicyConfig,
        HttpValidationError,
        IdentityResolutionResponse,
        IntegrationPromptResponse,
        LinkChallengeResponse,
        LinkUserRequest,
        MemoryDeleteResponse,
        MemoryDeleteResponseStatus,
        MemoryDeletionReceipt,
        MemoryDeletionReceiptOperation,
        MemoryFactResponse,
        MemoryProfileResponse,
        MemorySearchResponse,
        MemorySourceResponse,
        MemoryStoreResponse,
        OpenApiToolRegistrationRequest,
        OpenApiToolRegistrationResponse,
        ProjectListResponse,
        ProjectResponse,
        ProjectUpdate,
        ProjectUsageResponse,
        ResponsesOutputUsageDetails,
        ResponsesReasoning,
        ResponsesReasoningEffort,
        ResponsesResponse,
        ResponsesResponseObject,
        ResponsesResponseStatus,
        ResponsesUsage,
        ResponsesUsageDetails,
        ToolDiscoveryConfig,
        UnlinkResponse,
        ValidationError,
        ValidationErrorLocItem,
    )
    from .errors import ConflictError, UnprocessableEntityError
    from . import agent, responses
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .agent import MemorySearchRequestFactType, MemoryStoreRequestFactType
    from .client import AsyncGeneralAugmentClient, GeneralAugmentClient
    from .environment import GeneralAugmentClientEnvironment
    from .responses import ResponsesRequestReasoningEffort, ResponsesRequestTruncation
_dynamic_imports: typing.Dict[str, str] = {
    "AgentConfigUploadRequest": ".types",
    "AgentTestRequest": ".types",
    "AgentTestResponse": ".types",
    "ApprovalPolicyConfig": ".types",
    "AsyncGeneralAugmentClient": ".client",
    "ConflictError": ".errors",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "GeneralAugmentClient": ".client",
    "GeneralAugmentClientEnvironment": ".environment",
    "HttpValidationError": ".types",
    "IdentityResolutionResponse": ".types",
    "IntegrationPromptResponse": ".types",
    "LinkChallengeResponse": ".types",
    "LinkUserRequest": ".types",
    "MemoryDeleteResponse": ".types",
    "MemoryDeleteResponseStatus": ".types",
    "MemoryDeletionReceipt": ".types",
    "MemoryDeletionReceiptOperation": ".types",
    "MemoryFactResponse": ".types",
    "MemoryProfileResponse": ".types",
    "MemorySearchRequestFactType": ".agent",
    "MemorySearchResponse": ".types",
    "MemorySourceResponse": ".types",
    "MemoryStoreRequestFactType": ".agent",
    "MemoryStoreResponse": ".types",
    "OpenApiToolRegistrationRequest": ".types",
    "OpenApiToolRegistrationResponse": ".types",
    "ProjectListResponse": ".types",
    "ProjectResponse": ".types",
    "ProjectUpdate": ".types",
    "ProjectUsageResponse": ".types",
    "ResponsesOutputUsageDetails": ".types",
    "ResponsesReasoning": ".types",
    "ResponsesReasoningEffort": ".types",
    "ResponsesRequestReasoningEffort": ".responses",
    "ResponsesRequestTruncation": ".responses",
    "ResponsesResponse": ".types",
    "ResponsesResponseObject": ".types",
    "ResponsesResponseStatus": ".types",
    "ResponsesUsage": ".types",
    "ResponsesUsageDetails": ".types",
    "ToolDiscoveryConfig": ".types",
    "UnlinkResponse": ".types",
    "UnprocessableEntityError": ".errors",
    "ValidationError": ".types",
    "ValidationErrorLocItem": ".types",
    "agent": ".agent",
    "responses": ".responses",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentConfigUploadRequest",
    "AgentTestRequest",
    "AgentTestResponse",
    "ApprovalPolicyConfig",
    "AsyncGeneralAugmentClient",
    "ConflictError",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "GeneralAugmentClient",
    "GeneralAugmentClientEnvironment",
    "HttpValidationError",
    "IdentityResolutionResponse",
    "IntegrationPromptResponse",
    "LinkChallengeResponse",
    "LinkUserRequest",
    "MemoryDeleteResponse",
    "MemoryDeleteResponseStatus",
    "MemoryDeletionReceipt",
    "MemoryDeletionReceiptOperation",
    "MemoryFactResponse",
    "MemoryProfileResponse",
    "MemorySearchRequestFactType",
    "MemorySearchResponse",
    "MemorySourceResponse",
    "MemoryStoreRequestFactType",
    "MemoryStoreResponse",
    "OpenApiToolRegistrationRequest",
    "OpenApiToolRegistrationResponse",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectUpdate",
    "ProjectUsageResponse",
    "ResponsesOutputUsageDetails",
    "ResponsesReasoning",
    "ResponsesReasoningEffort",
    "ResponsesRequestReasoningEffort",
    "ResponsesRequestTruncation",
    "ResponsesResponse",
    "ResponsesResponseObject",
    "ResponsesResponseStatus",
    "ResponsesUsage",
    "ResponsesUsageDetails",
    "ToolDiscoveryConfig",
    "UnlinkResponse",
    "UnprocessableEntityError",
    "ValidationError",
    "ValidationErrorLocItem",
    "agent",
    "responses",
]
