// Curated public typed request/response models for the General Augment API.
//
// These interfaces are GENERATED by Fern from the curated public OpenAPI subset
// (see fern/curate_public_overlay.py) into src/_generated and re-exported here as
// the drift-checked typed contract for the SDK's public surface — the TypeScript
// mirror of Python's `genaug.types`.
//
// Like `genaug/types.py`, this re-export is CURATED: Fern generates a handful of
// internal plumbing types into src/_generated/api/types (ApprovalPolicyConfig,
// HttpValidationError, ValidationError, ToolDiscoveryConfig,
// ResponsesOutputUsageDetails, ResponsesReasoning) that Python deliberately omits
// from its public `__all__`; we omit them here too so the public typed surface
// matches Python exactly.
//
// The hand-written GeneralAugmentClient keeps its own hardened fetch transport and
// JsonObject-based payloads for backwards compatibility; import these models when
// you want static typing of the request/response shapes. Do NOT edit src/_generated
// by hand — regenerate with fern/regenerate.sh.

export type {
  AgentConfigUploadRequest,
  AgentTestRequest,
  AgentTestResponse,
  IdentityResolutionResponse,
  IntegrationPromptResponse,
  LinkChallengeResponse,
  LinkUserRequest,
  MemoryDeleteResponse,
  MemoryDeletionReceipt,
  MemoryFactResponse,
  MemoryProfileResponse,
  MemorySearchResponse,
  MemorySourceResponse,
  MemoryStoreResponse,
  OpenApiToolRegistrationRequest,
  OpenApiToolRegistrationResponse,
  ProjectListResponse,
  ProjectResponse,
  ProjectUpdate,
  ProjectUsageResponse,
  ResponsesResponse,
  ResponsesUsage,
  ResponsesUsageDetails,
  UnlinkResponse
} from "./_generated/api/types/index.js";
