# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.responses_reasoning import ResponsesReasoning
from ..types.responses_response import ResponsesResponse
from .raw_client import AsyncRawResponsesClient, RawResponsesClient
from .types.responses_request_reasoning_effort import ResponsesRequestReasoningEffort
from .types.responses_request_truncation import ResponsesRequestTruncation

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ResponsesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawResponsesClient
        """
        return self._raw_client

    def create_response(
        self,
        *,
        model: str,
        background: typing.Optional[bool] = OMIT,
        conversation: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        input: typing.Optional[typing.Any] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        max_output_tokens: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parallel_tool_calls: typing.Optional[bool] = OMIT,
        previous_response_id: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[ResponsesReasoning] = OMIT,
        reasoning_effort: typing.Optional[ResponsesRequestReasoningEffort] = OMIT,
        service_tier: typing.Optional[str] = OMIT,
        store: typing.Optional[bool] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        text: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        tool_choice: typing.Optional[typing.Any] = OMIT,
        tools: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        truncation: typing.Optional[ResponsesRequestTruncation] = OMIT,
        user: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResponsesResponse:
        """
        Create one Responses API-compatible agent response.

        Parameters
        ----------
        model : str

        background : typing.Optional[bool]

        conversation : typing.Optional[str]

        include : typing.Optional[typing.Sequence[str]]

        input : typing.Optional[typing.Any]

        instructions : typing.Optional[str]

        max_output_tokens : typing.Optional[int]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        parallel_tool_calls : typing.Optional[bool]

        previous_response_id : typing.Optional[str]

        reasoning : typing.Optional[ResponsesReasoning]

        reasoning_effort : typing.Optional[ResponsesRequestReasoningEffort]

        service_tier : typing.Optional[str]

        store : typing.Optional[bool]

        stream : typing.Optional[bool]

        temperature : typing.Optional[float]

        text : typing.Optional[typing.Dict[str, typing.Any]]

        tool_choice : typing.Optional[typing.Any]

        tools : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        top_p : typing.Optional[float]

        truncation : typing.Optional[ResponsesRequestTruncation]

        user : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesResponse
            Responses object. When request stream=true, the same object is emitted as semantic text/event-stream events.

        Examples
        --------
        from general_augment import GeneralAugmentClient

        client = GeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )
        client.responses.create_response(
            model="model",
        )
        """
        _response = self._raw_client.create_response(
            model=model,
            background=background,
            conversation=conversation,
            include=include,
            input=input,
            instructions=instructions,
            max_output_tokens=max_output_tokens,
            metadata=metadata,
            parallel_tool_calls=parallel_tool_calls,
            previous_response_id=previous_response_id,
            reasoning=reasoning,
            reasoning_effort=reasoning_effort,
            service_tier=service_tier,
            store=store,
            stream=stream,
            temperature=temperature,
            text=text,
            tool_choice=tool_choice,
            tools=tools,
            top_p=top_p,
            truncation=truncation,
            user=user,
            request_options=request_options,
        )
        return _response.data


class AsyncResponsesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawResponsesClient
        """
        return self._raw_client

    async def create_response(
        self,
        *,
        model: str,
        background: typing.Optional[bool] = OMIT,
        conversation: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        input: typing.Optional[typing.Any] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        max_output_tokens: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parallel_tool_calls: typing.Optional[bool] = OMIT,
        previous_response_id: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[ResponsesReasoning] = OMIT,
        reasoning_effort: typing.Optional[ResponsesRequestReasoningEffort] = OMIT,
        service_tier: typing.Optional[str] = OMIT,
        store: typing.Optional[bool] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        text: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        tool_choice: typing.Optional[typing.Any] = OMIT,
        tools: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        truncation: typing.Optional[ResponsesRequestTruncation] = OMIT,
        user: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResponsesResponse:
        """
        Create one Responses API-compatible agent response.

        Parameters
        ----------
        model : str

        background : typing.Optional[bool]

        conversation : typing.Optional[str]

        include : typing.Optional[typing.Sequence[str]]

        input : typing.Optional[typing.Any]

        instructions : typing.Optional[str]

        max_output_tokens : typing.Optional[int]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        parallel_tool_calls : typing.Optional[bool]

        previous_response_id : typing.Optional[str]

        reasoning : typing.Optional[ResponsesReasoning]

        reasoning_effort : typing.Optional[ResponsesRequestReasoningEffort]

        service_tier : typing.Optional[str]

        store : typing.Optional[bool]

        stream : typing.Optional[bool]

        temperature : typing.Optional[float]

        text : typing.Optional[typing.Dict[str, typing.Any]]

        tool_choice : typing.Optional[typing.Any]

        tools : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        top_p : typing.Optional[float]

        truncation : typing.Optional[ResponsesRequestTruncation]

        user : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesResponse
            Responses object. When request stream=true, the same object is emitted as semantic text/event-stream events.

        Examples
        --------
        import asyncio

        from general_augment import AsyncGeneralAugmentClient

        client = AsyncGeneralAugmentClient(
            project_id="YOUR_PROJECT_ID",
            admin_key="YOUR_ADMIN_KEY",
        )


        async def main() -> None:
            await client.responses.create_response(
                model="model",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_response(
            model=model,
            background=background,
            conversation=conversation,
            include=include,
            input=input,
            instructions=instructions,
            max_output_tokens=max_output_tokens,
            metadata=metadata,
            parallel_tool_calls=parallel_tool_calls,
            previous_response_id=previous_response_id,
            reasoning=reasoning,
            reasoning_effort=reasoning_effort,
            service_tier=service_tier,
            store=store,
            stream=stream,
            temperature=temperature,
            text=text,
            tool_choice=tool_choice,
            tools=tools,
            top_p=top_p,
            truncation=truncation,
            user=user,
            request_options=request_options,
        )
        return _response.data
