# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.conflict_error import ConflictError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from ..types.responses_reasoning import ResponsesReasoning
from ..types.responses_response import ResponsesResponse
from .types.responses_request_reasoning_effort import ResponsesRequestReasoningEffort
from .types.responses_request_truncation import ResponsesRequestTruncation
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawResponsesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_response(
        self,
        *,
        model: str,
        background: typing.Optional[bool] = OMIT,
        conversation: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        input: typing.Optional[typing.Any] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        max_output_tokens: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parallel_tool_calls: typing.Optional[bool] = OMIT,
        previous_response_id: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[ResponsesReasoning] = OMIT,
        reasoning_effort: typing.Optional[ResponsesRequestReasoningEffort] = OMIT,
        service_tier: typing.Optional[str] = OMIT,
        store: typing.Optional[bool] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        text: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        tool_choice: typing.Optional[typing.Any] = OMIT,
        tools: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        truncation: typing.Optional[ResponsesRequestTruncation] = OMIT,
        user: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ResponsesResponse]:
        """
        Create one Responses API-compatible agent response.

        Parameters
        ----------
        model : str

        background : typing.Optional[bool]

        conversation : typing.Optional[str]

        include : typing.Optional[typing.Sequence[str]]

        input : typing.Optional[typing.Any]

        instructions : typing.Optional[str]

        max_output_tokens : typing.Optional[int]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        parallel_tool_calls : typing.Optional[bool]

        previous_response_id : typing.Optional[str]

        reasoning : typing.Optional[ResponsesReasoning]

        reasoning_effort : typing.Optional[ResponsesRequestReasoningEffort]

        service_tier : typing.Optional[str]

        store : typing.Optional[bool]

        stream : typing.Optional[bool]

        temperature : typing.Optional[float]

        text : typing.Optional[typing.Dict[str, typing.Any]]

        tool_choice : typing.Optional[typing.Any]

        tools : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        top_p : typing.Optional[float]

        truncation : typing.Optional[ResponsesRequestTruncation]

        user : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResponsesResponse]
            Responses object. When request stream=true, the same object is emitted as semantic text/event-stream events.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/responses",
            method="POST",
            json={
                "background": background,
                "conversation": conversation,
                "include": include,
                "input": input,
                "instructions": instructions,
                "max_output_tokens": max_output_tokens,
                "metadata": metadata,
                "model": model,
                "parallel_tool_calls": parallel_tool_calls,
                "previous_response_id": previous_response_id,
                "reasoning": convert_and_respect_annotation_metadata(
                    object_=reasoning, annotation=typing.Optional[ResponsesReasoning], direction="write"
                ),
                "reasoning_effort": reasoning_effort,
                "service_tier": service_tier,
                "store": store,
                "stream": stream,
                "temperature": temperature,
                "text": text,
                "tool_choice": tool_choice,
                "tools": tools,
                "top_p": top_p,
                "truncation": truncation,
                "user": user,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResponsesResponse,
                    parse_obj_as(
                        type_=ResponsesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawResponsesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_response(
        self,
        *,
        model: str,
        background: typing.Optional[bool] = OMIT,
        conversation: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        input: typing.Optional[typing.Any] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        max_output_tokens: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parallel_tool_calls: typing.Optional[bool] = OMIT,
        previous_response_id: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[ResponsesReasoning] = OMIT,
        reasoning_effort: typing.Optional[ResponsesRequestReasoningEffort] = OMIT,
        service_tier: typing.Optional[str] = OMIT,
        store: typing.Optional[bool] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        text: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        tool_choice: typing.Optional[typing.Any] = OMIT,
        tools: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        truncation: typing.Optional[ResponsesRequestTruncation] = OMIT,
        user: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ResponsesResponse]:
        """
        Create one Responses API-compatible agent response.

        Parameters
        ----------
        model : str

        background : typing.Optional[bool]

        conversation : typing.Optional[str]

        include : typing.Optional[typing.Sequence[str]]

        input : typing.Optional[typing.Any]

        instructions : typing.Optional[str]

        max_output_tokens : typing.Optional[int]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        parallel_tool_calls : typing.Optional[bool]

        previous_response_id : typing.Optional[str]

        reasoning : typing.Optional[ResponsesReasoning]

        reasoning_effort : typing.Optional[ResponsesRequestReasoningEffort]

        service_tier : typing.Optional[str]

        store : typing.Optional[bool]

        stream : typing.Optional[bool]

        temperature : typing.Optional[float]

        text : typing.Optional[typing.Dict[str, typing.Any]]

        tool_choice : typing.Optional[typing.Any]

        tools : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        top_p : typing.Optional[float]

        truncation : typing.Optional[ResponsesRequestTruncation]

        user : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResponsesResponse]
            Responses object. When request stream=true, the same object is emitted as semantic text/event-stream events.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/responses",
            method="POST",
            json={
                "background": background,
                "conversation": conversation,
                "include": include,
                "input": input,
                "instructions": instructions,
                "max_output_tokens": max_output_tokens,
                "metadata": metadata,
                "model": model,
                "parallel_tool_calls": parallel_tool_calls,
                "previous_response_id": previous_response_id,
                "reasoning": convert_and_respect_annotation_metadata(
                    object_=reasoning, annotation=typing.Optional[ResponsesReasoning], direction="write"
                ),
                "reasoning_effort": reasoning_effort,
                "service_tier": service_tier,
                "store": store,
                "stream": stream,
                "temperature": temperature,
                "text": text,
                "tool_choice": tool_choice,
                "tools": tools,
                "top_p": top_p,
                "truncation": truncation,
                "user": user,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResponsesResponse,
                    parse_obj_as(
                        type_=ResponsesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
