// This file was auto-generated by Fern from our API Definition.

export const GeneralAugmentEnvironment = {
    Production: "https://api.generalaugment.com",
} as const;

export type GeneralAugmentEnvironment = typeof GeneralAugmentEnvironment.Production;
