"""Safe app migration commands."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Annotated

import typer

from platform_cli.errors import CLIError
from platform_cli.openai_responses_migration import plan_openai_responses_migration
from platform_cli.output import print_json, print_success, print_warning, table
from platform_cli.runtime import Runtime
from platform_cli.self_serve import artifact_dir, build_setup_payload, write_payload

app = typer.Typer(help="Safely migrate an existing app to General Augment.")


@app.command("openai-responses")
def migrate_openai_responses(
    ctx: typer.Context,
    workspace: Annotated[
        Path,
        typer.Option(help="App workspace to inspect and optionally patch."),
    ] = Path("."),
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Generate a diff without applying changes."),
    ] = False,
    apply: Annotated[
        bool,
        typer.Option("--apply", help="Apply known-safe migration edits after confirmation."),
    ] = False,
    yes: Annotated[
        bool,
        typer.Option("--yes", help="Skip confirmation when used with --apply."),
    ] = False,
    project: Annotated[str | None, typer.Option(help="Project id, slug, or name.")] = None,
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", help="Write the migration plan JSON to this path."),
    ] = None,
    branch: Annotated[
        str | None,
        typer.Option("--branch", help="Create a branch before applying migration edits."),
    ] = None,
    commit_message: Annotated[
        str,
        typer.Option("--commit-message", help="Commit message for --create-pr workflows."),
    ] = "Migrate OpenAI Responses calls to General Augment",
    push: Annotated[
        bool,
        typer.Option("--push", help="Push the migration branch after committing."),
    ] = False,
    create_pr: Annotated[
        bool,
        typer.Option("--create-pr", help="Open a GitHub pull request with gh after applying."),
    ] = False,
    pr_title: Annotated[
        str | None,
        typer.Option("--pr-title", help="Pull request title. Defaults to --commit-message."),
    ] = None,
    pr_body: Annotated[
        str,
        typer.Option("--pr-body", help="Pull request body for --create-pr."),
    ] = "Generated by `genaug migrate openai-responses`.",
    json_output: Annotated[
        bool,
        typer.Option("--json", help="Print machine-readable JSON."),
    ] = False,
) -> None:
    """Migrate OpenAI Responses-compatible calls to the General Augment endpoint."""
    runtime: Runtime = ctx.obj
    if apply and dry_run:
        raise CLIError("Use either --dry-run or --apply, not both.")
    if (branch or push or create_pr) and not apply:
        raise CLIError("Git and pull-request migration options require --apply.")
    if (push or create_pr) and not branch:
        raise CLIError("Pass --branch when using --push or --create-pr.")
    should_apply = bool(apply)
    if should_apply and not yes and not typer.confirm("Apply General Augment migration edits?"):
        raise typer.Exit(1)
    if should_apply and branch:
        _run_command(["git", "switch", "-c", branch], cwd=workspace)
    migration = plan_openai_responses_migration(
        workspace,
        apply=should_apply,
        artifact_dir=artifact_dir(workspace),
    )
    pull_request = _finalize_pull_request(
        workspace=workspace,
        migration=migration,
        branch=branch,
        commit_message=commit_message,
        push=push or create_pr,
        create_pr=create_pr,
        pr_title=pr_title or commit_message,
        pr_body=pr_body,
    )
    payload = build_setup_payload(
        workspace=workspace,
        config=runtime.config,
        requested_capabilities=[],
        project=project,
        migration=migration,
        mode="migrate",
    )
    payload["pull_request"] = pull_request
    artifact_path = write_payload(payload, output, workspace)
    payload["artifact_path"] = str(artifact_path)
    artifact_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    # An agent gates on the exit code, so "no OpenAI client could be migrated" must
    # fail honestly rather than report a successful no-op.
    changed = bool(migration.get("changed"))
    warnings: list[str] = migration.get("warnings", []) if isinstance(migration, dict) else []
    if json_output:
        print_json(payload)
        if not changed:
            raise typer.Exit(1)
        return
    table(
        "OpenAI Responses migration",
        ["Field", "Value"],
        [
            ["Mode", "apply" if should_apply else "dry-run"],
            ["Diff", migration["diff_path"]],
            ["Files", ", ".join(migration["diff_files"]) or "none"],
            ["Pull request", pull_request["url"] if pull_request else "not requested"],
            ["Artifact", artifact_path],
        ],
    )
    for warning in warnings:
        print_warning(f"Needs attention: {warning}")
    if not changed:
        print_warning(
            "No OpenAI client config was migrated. Review the warnings above and "
            "migrate any clients manually; nothing in your app was changed."
        )
        raise typer.Exit(1)
    print_success(
        "Migration edits applied."
        if should_apply
        else "Migration diff generated without changing app code."
    )


def _finalize_pull_request(
    *,
    workspace: Path,
    migration: dict[str, object],
    branch: str | None,
    commit_message: str,
    push: bool,
    create_pr: bool,
    pr_title: str,
    pr_body: str,
) -> dict[str, object] | None:
    """Commit, push, and optionally open a PR for an applied migration."""
    if not branch and not create_pr and not push:
        return None
    changed_files = _changed_files(migration)
    if not changed_files:
        raise CLIError("No migration files changed; refusing to create an empty pull request.")
    _run_command(["git", "add", *changed_files], cwd=workspace)
    _run_command(["git", "commit", "-m", commit_message], cwd=workspace)
    if push:
        _run_command(["git", "push", "-u", "origin", branch or "HEAD"], cwd=workspace)
    url = None
    if create_pr:
        url = _run_command(
            [
                "gh",
                "pr",
                "create",
                "--fill",
                "--title",
                pr_title,
                "--body",
                pr_body,
            ],
            cwd=workspace,
        ).strip()
    return {
        "requested": create_pr,
        "branch": branch,
        "commit_message": commit_message,
        "pushed": push,
        "url": url,
    }


def _changed_files(migration: dict[str, object]) -> list[str]:
    """Return relative files that should be committed for the migration patch."""
    files: list[str] = []
    diff_files = migration.get("diff_files", [])
    if isinstance(diff_files, list):
        files.extend(str(item) for item in diff_files)
    env = migration.get("env")
    if isinstance(env, dict):
        written_files = env.get("written_files", [])
        if isinstance(written_files, list):
            files.extend(str(item) for item in written_files)
    seen: set[str] = set()
    unique_files: list[str] = []
    for item in files:
        if not item or item in seen:
            continue
        seen.add(item)
        unique_files.append(item)
    return unique_files


def _run_command(command: list[str], *, cwd: Path) -> str:
    """Run a local git/GitHub CLI command for PR-based migrations."""
    try:
        completed = subprocess.run(
            command,
            cwd=cwd.expanduser().resolve(),
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise CLIError(f"Required command not found: {command[0]}") from exc
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or str(exc)).strip()
        if len(detail) > 400:
            detail = f"{detail[:397]}..."
        raise CLIError(f"Command failed: {' '.join(command)}\n{detail}") from exc
    return completed.stdout.strip()
