// This file was auto-generated by Fern from our API Definition.

/**
 * Payload for importing a `genaug-agent.yaml` document.
 */
export interface AgentConfigUploadRequest {
    skills?: string[] | undefined;
    soul_content?: (string | null) | undefined;
    yaml_content: string;
}
