// This file was auto-generated by Fern from our API Definition.

/**
 * Agent test endpoint response.
 */
export interface AgentTestResponse {
    cost_usd?: number | undefined;
    details?: (string | null) | undefined;
    error?: (string | null) | undefined;
    metadata?: Record<string, unknown> | undefined;
    model_used?: (string | null) | undefined;
    response?: (string | null) | undefined;
    response_text?: string | undefined;
    suggestion?: (string | null) | undefined;
    warnings?: string[] | undefined;
}
