// This file was auto-generated by Fern from our API Definition.

/**
 * Payload for testing an agent without a live channel.
 */
export interface AgentTestRequest {
    agent_id?: (string | null) | undefined;
    channel?: string | undefined;
    message: string;
    phone_e164?: string | undefined;
}
