// This file was auto-generated by Fern from our API Definition.

/**
 * Tenant controls for when platform-managed tools require approval.
 */
export interface ApprovalPolicyConfig {
    mode?: string | undefined;
}
