// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

export interface HttpValidationError {
    detail?: GeneralAugment.ValidationError[] | undefined;
}
