// This file was auto-generated by Fern from our API Definition.

/**
 * Resolved external app identity response.
 */
export interface IdentityResolutionResponse {
    linked_at: string | null;
    metadata?: Record<string, unknown> | undefined;
    phone_e164: string;
    project_id: string;
    provider_name: string;
    provider_user_id: string;
}
