// This file was auto-generated by Fern from our API Definition.

/**
 * Challenge response returned after a link is initiated.
 */
export interface LinkChallengeResponse {
    debug_verification_code?: (string | null) | undefined;
    id: string;
    magic_link?: (string | null) | undefined;
    phone_e164: string;
    provider_name: string;
    provider_user_id: string;
    verification_expires_at: string;
}
