// This file was auto-generated by Fern from our API Definition.

/**
 * App-initiated linking request payload.
 */
export interface LinkUserRequest {
    metadata?: Record<string, unknown> | undefined;
    phone_e164: string;
    provider_name: string;
    provider_user_id: string;
}
