// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Response returned after deleting selected memory facts.
 */
export interface MemoryDeleteResponse {
    deleted_count: number;
    deleted_ids?: string[] | undefined;
    general_augment_user_id: string;
    memory_id?: (string | null) | undefined;
    receipt: GeneralAugment.MemoryDeletionReceipt;
    status: MemoryDeleteResponse.Status;
    user_id: string;
}

export namespace MemoryDeleteResponse {
    export const Status = {
        Deleted: "deleted",
        NotFound: "not_found",
        Purged: "purged",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
