// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Semantic memory search response.
 */
export interface MemorySearchResponse {
    facts: GeneralAugment.MemoryFactResponse[];
    general_augment_user_id: string;
    user_id: string;
}
