// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Persisted memory profile for one tenant user.
 */
export interface MemoryProfileResponse {
    general_augment_user_id: string;
    profile: Record<string, unknown>;
    recent_facts: GeneralAugment.MemoryFactResponse[];
    total_facts: number;
    user_id: string;
}
