// This file was auto-generated by Fern from our API Definition.

/**
 * Serialized memory fact returned by the tenant-facing API.
 */
export interface MemoryFactResponse {
    collection_key?: string | undefined;
    consolidation_group_id?: (string | null) | undefined;
    content: string;
    contradicts_memory_id?: (string | null) | undefined;
    created_at: string;
    expires_at?: (string | null) | undefined;
    fact_type: string;
    id: string;
    importance_score: number;
    metadata?: Record<string, unknown> | undefined;
    parent_memory_id?: (string | null) | undefined;
    provenance?: Record<string, unknown> | undefined;
    similarity?: (number | null) | undefined;
    source?: (string | null) | undefined;
    status?: string | undefined;
    supersedes_memory_id?: (string | null) | undefined;
}
