// This file was auto-generated by Fern from our API Definition.

/**
 * Receipt returned after a tenant-facing memory delete request commits.
 */
export interface MemoryDeletionReceipt {
    deleted_count: number;
    issued_at: string;
    operation: MemoryDeletionReceipt.Operation;
    receipt_id: string;
}

export namespace MemoryDeletionReceipt {
    export const Operation = {
        MemoryDelete: "memory_delete",
        MemoryPurge: "memory_purge",
        MemorySuppress: "memory_suppress",
    } as const;
    export type Operation = (typeof Operation)[keyof typeof Operation];
}
