// This file was auto-generated by Fern from our API Definition.

/**
 * Project-scoped memory source registry evidence.
 */
export interface MemorySourceResponse {
    fact_count: number;
    id: string;
    last_seen_at?: (string | null) | undefined;
    metadata?: Record<string, unknown> | undefined;
    source_key: string;
    source_type: string;
    status: string;
    trust_level: string;
}
