// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Response returned after storing a memory fact.
 */
export interface MemoryStoreResponse {
    collection_key?: string | undefined;
    content: string;
    general_augment_user_id: string;
    memory_id: string;
    metadata?: Record<string, unknown> | undefined;
    source?: (string | null) | undefined;
    source_info?: (GeneralAugment.MemorySourceResponse | null) | undefined;
    status?: string | undefined;
    user_id: string;
}
