// This file was auto-generated by Fern from our API Definition.

/**
 * Curated generated tool registration response.
 */
export interface OpenApiToolRegistrationResponse {
    api_title: string;
    auto_deployed: boolean;
    curated_count: number;
    enabled_tool_ids: string[];
    endpoint_count: number;
    generated_count: number;
    mcp_server: Record<string, unknown>;
    tools: Record<string, unknown>[];
}
