// This file was auto-generated by Fern from our API Definition.

/**
 * Payload for generating project tools from an OpenAPI specification.
 */
export interface OpenApiToolRegistrationRequest {
    auto_deploy?: boolean | undefined;
    exclude_paths?: string[] | undefined;
    include_paths?: string[] | undefined;
    name_prefix?: (string | null) | undefined;
    spec_url: string;
    target_count?: number | undefined;
}
