// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Project list response.
 */
export interface ProjectListResponse {
    items: GeneralAugment.ProjectResponse[];
}
