// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Payload for updating a project tenant.
 */
export interface ProjectUpdate {
    approval_webhook_url?: (string | null) | undefined;
    billing_webhook_url?: (string | null) | undefined;
    branding?: (Record<string, unknown> | null) | undefined;
    enabled_tool_ids?: (string[] | null) | undefined;
    local_connectors?: (Record<string, unknown>[] | null) | undefined;
    mcp_servers?: (Record<string, unknown>[] | null) | undefined;
    model_preferences?: (Record<string, string | null> | null) | undefined;
    name?: (string | null) | undefined;
    plan?: (string | null) | undefined;
    platform_webhook_url?: (string | null) | undefined;
    pricing_tier?: (string | null) | undefined;
    rate_limits?: (Record<string, unknown> | null) | undefined;
    security_flags?: (Record<string, unknown> | null) | undefined;
    slug?: (string | null) | undefined;
    status?: (string | null) | undefined;
    system_prompt?: (string | null) | undefined;
    telegram_bot_token?: (string | null) | undefined;
    tool_discovery?: (GeneralAugment.ToolDiscoveryConfig | null) | undefined;
    twilio_phone_number?: (string | null) | undefined;
    webhook_secret?: (string | null) | undefined;
    whatsapp_phone_number_id?: (string | null) | undefined;
}
