// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Serialized project tenant.
 */
export interface ProjectResponse {
    approval_webhook_url?: (string | null) | undefined;
    billing_webhook_url?: (string | null) | undefined;
    branding: Record<string, unknown>;
    created_at: string;
    enabled_tool_ids: string[];
    id: string;
    langfuse_project_id?: (string | null) | undefined;
    langfuse_public_key?: (string | null) | undefined;
    /** Human-owned launch authorization policy. Manifests and installer credentials cannot change this value. */
    launch_approval_policy?: string | undefined;
    local_connectors?: Record<string, unknown>[] | undefined;
    mcp_servers: Record<string, unknown>[];
    model_preferences: Record<string, string>;
    name: string;
    plan?: string | undefined;
    platform_webhook_url?: (string | null) | undefined;
    pricing_tier?: string | undefined;
    rate_limits: Record<string, unknown>;
    security_flags: Record<string, unknown>;
    slug: string;
    status: string;
    stripe_customer_id?: (string | null) | undefined;
    system_prompt: string;
    /** Whether Telegram credentials are configured without exposing token material. */
    telegram_bot_configured?: boolean | undefined;
    /** Always redacted to null in project responses; use telegram_bot_configured for status. */
    telegram_bot_token?: (string | null) | undefined;
    tool_discovery?: GeneralAugment.ToolDiscoveryConfig | undefined;
    twilio_phone_number: string | null;
    updated_at: string;
    /** Always redacted to null in project responses; send webhook_secret only when rotating the value. */
    webhook_secret?: (string | null) | undefined;
    /** Whether a project webhook secret exists without exposing secret material. */
    webhook_secret_configured?: boolean | undefined;
    /** Display-only project webhook secret preview. */
    webhook_secret_preview?: (string | null) | undefined;
    whatsapp_phone_number_id: string | null;
    workspace_id?: (string | null) | undefined;
}
