// This file was auto-generated by Fern from our API Definition.

/**
 * Detailed usage and cost aggregates for one project.
 */
export interface ProjectUsageResponse {
    days: Record<string, unknown>[];
    end_date: string;
    limits?: Record<string, unknown> | undefined;
    project_id: string;
    start_date: string;
    totals: Record<string, unknown>;
}
