// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Responses-compatible usage payload.
 */
export interface ResponsesUsage {
    input_tokens?: number | undefined;
    input_tokens_details?: GeneralAugment.ResponsesUsageDetails | undefined;
    output_tokens?: number | undefined;
    output_tokens_details?: GeneralAugment.ResponsesOutputUsageDetails | undefined;
    total_tokens?: number | undefined;
}
