// This file was auto-generated by Fern from our API Definition.

/**
 * Responses-compatible reasoning controls.
 */
export interface ResponsesReasoning {
    effort?: (ResponsesReasoning.Effort | null) | undefined;
    summary?: (unknown | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace ResponsesReasoning {
    export const Effort = {
        None: "none",
        Minimal: "minimal",
        Low: "low",
        Medium: "medium",
        High: "high",
        Xhigh: "xhigh",
    } as const;
    export type Effort = (typeof Effort)[keyof typeof Effort];
}
