// This file was auto-generated by Fern from our API Definition.

/**
 * Responses-compatible output token details.
 */
export interface ResponsesOutputUsageDetails {
    reasoning_tokens?: number | undefined;
}
