// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Open Responses-compatible response object.
 */
export interface ResponsesResponse {
    created_at: number;
    error?: (Record<string, unknown> | null) | undefined;
    id: string;
    incomplete_details?: (Record<string, unknown> | null) | undefined;
    instructions?: (string | null) | undefined;
    metadata?: Record<string, unknown> | undefined;
    model: string;
    object?: ResponsesResponse.Object_ | undefined;
    output: Record<string, unknown>[];
    previous_response_id?: (string | null) | undefined;
    reasoning?: GeneralAugment.ResponsesReasoning | undefined;
    status: ResponsesResponse.Status;
    temperature?: (number | null) | undefined;
    tools?: Record<string, unknown>[] | undefined;
    top_p?: (number | null) | undefined;
    usage: GeneralAugment.ResponsesUsage;
}

export namespace ResponsesResponse {
    export const Object_ = {
        Response: "response",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
    export const Status = {
        Queued: "queued",
        InProgress: "in_progress",
        Completed: "completed",
        Failed: "failed",
        Incomplete: "incomplete",
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
