// This file was auto-generated by Fern from our API Definition.

import type * as GeneralAugment from "../index.js";

/**
 * Tenant controls for how Hermes sees enabled tools.
 */
export interface ToolDiscoveryConfig {
    allow_runtime_skill_writes?: boolean | undefined;
    approval_policy?: GeneralAugment.ApprovalPolicyConfig | undefined;
    direct_schema_tool_limit?: number | undefined;
    hermes_runtime?: Record<string, unknown> | undefined;
    max_search_results?: number | undefined;
    mode?: string | undefined;
    native_hermes_toolsets?: string[] | undefined;
}
